#spring.application.name=web-store
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=1234
#
#server.port=8080
#
#spring.jpa.hibernate.ddl-auto=update

server:
  port: 8080
spring:
  application:
    name: web-store
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true